# Generated by Django 3.0.5 on 2020-04-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pro_images'),
        ),
    ]
