# Generated by Django 3.0.5 on 2020-04-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_contactprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='vehicleprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='contactprofile',
            name='cdl',
            field=models.ImageField(blank=True, upload_to='contact_cdl'),
        ),
        migrations.AddField(
            model_name='vehicleprofile',
            name='veh_picture',
            field=models.ImageField(blank=True, upload_to='veh_images'),
        ),
        migrations.AlterField(
            model_name='permitprofile',
            name='pdf',
            field=models.FileField(blank=True, upload_to='permit_pdf'),
        ),
    ]
