# Generated by Django 3.0.5 on 2020-04-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0003_auto_20200409_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleprofile',
            name='attached_to',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
